# Generated by Django 6.0.3 on 2026-04-04 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reset_otp',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
